### ISSUE TITLE
README fails to mention how to use this

### ISSUE THREAD

**Issue by rubydesign** [orbitalimpact/three.rb#1]
Hi,
i was looking at using three from opal and found this.
I would even be willing to contribute, but it seems early days, yes ?
Could you add a little as to what the layer does? What kind of "magical" conversions of calls/constants etc.
Possibly a howto for static usage.

**Comment by ylluminarious** [comment]
@dancinglightning Hi, thanks for mentioning this. I had totally forgot to show a usage example in the README :stuck_out_tongue_winking_eye:. If you'll look there now, you'll see that the `demo` directory is currently the only working example of three.rb, so yes, we are kind of in the early days of development of this library.

If you're curious about the current API, you can check out [`demo/app/main.rb`](https://github.com/orbitalimpact/three.rb/blob/master/demo/app/main.rb) and get a feel for what it is like right now.

Also, if you feel like contributing you're certainly welcome to :)

**Comment by ylluminarious** [comment]
@dancinglightning Btw, I just [created a room on Gitter](https://gitter.im/orbitalimpact/three.rb) if you feel like chatting about three.rb, or anyone else for that matter.
